### ISSUE TITLE
Issue building 2nd vignette 

### ISSUE THREAD

**Issue by theoroe3** [jr-packages/jrProgBio#2]
Hi @rmnppt , when adding the package to travis I get this build error

Quitting from lines 70-71 (./practical2_contents.Rmd) 
Quitting from lines 29-33 (./practical2_contents.Rmd) 
Error: processing vignette 'practical2.Rmd' failed with diagnostics:
object 'group' not found
In addition: Warning message:
In tools::buildVignettes(dir = ".", tangle = TRUE) :
  Files named as vignettes but with no recognized vignette engine:
   ‘vignettes/practical2_contents.Rmd’
(Is a VignetteBuilder field missing?) 

Could you have a look at it please? Cheers

**Comment by rmnppt** [comment]
Just pushed some changes - lets look at the latest build on travis when its done.

**Comment by theoroe3** [comment]
@rmnppt it's failed again, but this time only because the data set "malaria" doesn't have any documentation

**Comment by rmnppt** [comment]
ok ill get onto that now...

**Comment by theoroe3** [comment]
wahooo build complete
