### ISSUE TITLE
Failing on practical 3

### ISSUE THREAD

**Issue by rmnppt** [jr-packages/jrProgBio#4]
@csgillespie Failing to compile practical 3 (sweave). Is there a fix or do we need to convert to .Rmd?

**Comment by csgillespie** [comment]
I think the practical is actually knitr not sweave, but has the wrong file extension. We (might) get away with this in the Prog package because the pdf is already there (perhaps).

Try changing the file extension

**Comment by rmnppt** [comment]
nah still getting errors with `devtools::check()`

shouldn't be too difficult to convert to .Rmd using the others as a starting point right? Or is there something particular about 3?

I can make a start on that if you like and see where I get to.

**Comment by csgillespie** [comment]
Please convert. Ta

**Comment by rmnppt** [comment]
adding the files that are needed for 3 fixed it. Fingers crossed its ok now.
